/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecurringRouteImport } from './routes/recurring'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as LogRouteImport } from './routes/log'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BattlesIndexRouteImport } from './routes/battles.index'
import { Route as BattlesIdRouteImport } from './routes/battles.$id'
import { Route as AuthMagicRouteImport } from './routes/auth.magic'
import { Route as BattlesIdIndexRouteImport } from './routes/battles.$id.index'
import { Route as BattlesIdResultsYmRouteImport } from './routes/battles.$id.results.$ym'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringRoute = RecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlesIndexRoute = BattlesIndexRouteImport.update({
  id: '/battles/',
  path: '/battles/',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlesIdRoute = BattlesIdRouteImport.update({
  id: '/battles/$id',
  path: '/battles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMagicRoute = AuthMagicRouteImport.update({
  id: '/auth/magic',
  path: '/auth/magic',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlesIdIndexRoute = BattlesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BattlesIdRoute,
} as any)
const BattlesIdResultsYmRoute = BattlesIdResultsYmRouteImport.update({
  id: '/results/$ym',
  path: '/results/$ym',
  getParentRoute: () => BattlesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/onboard': typeof OnboardRoute
  '/recurring': typeof RecurringRoute
  '/settings': typeof SettingsRoute
  '/auth/magic': typeof AuthMagicRoute
  '/battles/$id': typeof BattlesIdRouteWithChildren
  '/battles/': typeof BattlesIndexRoute
  '/battles/$id/': typeof BattlesIdIndexRoute
  '/battles/$id/results/$ym': typeof BattlesIdResultsYmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/onboard': typeof OnboardRoute
  '/recurring': typeof RecurringRoute
  '/settings': typeof SettingsRoute
  '/auth/magic': typeof AuthMagicRoute
  '/battles': typeof BattlesIndexRoute
  '/battles/$id': typeof BattlesIdIndexRoute
  '/battles/$id/results/$ym': typeof BattlesIdResultsYmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/onboard': typeof OnboardRoute
  '/recurring': typeof RecurringRoute
  '/settings': typeof SettingsRoute
  '/auth/magic': typeof AuthMagicRoute
  '/battles/$id': typeof BattlesIdRouteWithChildren
  '/battles/': typeof BattlesIndexRoute
  '/battles/$id/': typeof BattlesIdIndexRoute
  '/battles/$id/results/$ym': typeof BattlesIdResultsYmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/log'
    | '/onboard'
    | '/recurring'
    | '/settings'
    | '/auth/magic'
    | '/battles/$id'
    | '/battles/'
    | '/battles/$id/'
    | '/battles/$id/results/$ym'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/log'
    | '/onboard'
    | '/recurring'
    | '/settings'
    | '/auth/magic'
    | '/battles'
    | '/battles/$id'
    | '/battles/$id/results/$ym'
  id:
    | '__root__'
    | '/'
    | '/log'
    | '/onboard'
    | '/recurring'
    | '/settings'
    | '/auth/magic'
    | '/battles/$id'
    | '/battles/'
    | '/battles/$id/'
    | '/battles/$id/results/$ym'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogRoute: typeof LogRoute
  OnboardRoute: typeof OnboardRoute
  RecurringRoute: typeof RecurringRoute
  SettingsRoute: typeof SettingsRoute
  AuthMagicRoute: typeof AuthMagicRoute
  BattlesIdRoute: typeof BattlesIdRouteWithChildren
  BattlesIndexRoute: typeof BattlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring': {
      id: '/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof RecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battles/': {
      id: '/battles/'
      path: '/battles'
      fullPath: '/battles/'
      preLoaderRoute: typeof BattlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battles/$id': {
      id: '/battles/$id'
      path: '/battles/$id'
      fullPath: '/battles/$id'
      preLoaderRoute: typeof BattlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/magic': {
      id: '/auth/magic'
      path: '/auth/magic'
      fullPath: '/auth/magic'
      preLoaderRoute: typeof AuthMagicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battles/$id/': {
      id: '/battles/$id/'
      path: '/'
      fullPath: '/battles/$id/'
      preLoaderRoute: typeof BattlesIdIndexRouteImport
      parentRoute: typeof BattlesIdRoute
    }
    '/battles/$id/results/$ym': {
      id: '/battles/$id/results/$ym'
      path: '/results/$ym'
      fullPath: '/battles/$id/results/$ym'
      preLoaderRoute: typeof BattlesIdResultsYmRouteImport
      parentRoute: typeof BattlesIdRoute
    }
  }
}

interface BattlesIdRouteChildren {
  BattlesIdIndexRoute: typeof BattlesIdIndexRoute
  BattlesIdResultsYmRoute: typeof BattlesIdResultsYmRoute
}

const BattlesIdRouteChildren: BattlesIdRouteChildren = {
  BattlesIdIndexRoute: BattlesIdIndexRoute,
  BattlesIdResultsYmRoute: BattlesIdResultsYmRoute,
}

const BattlesIdRouteWithChildren = BattlesIdRoute._addFileChildren(
  BattlesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogRoute: LogRoute,
  OnboardRoute: OnboardRoute,
  RecurringRoute: RecurringRoute,
  SettingsRoute: SettingsRoute,
  AuthMagicRoute: AuthMagicRoute,
  BattlesIdRoute: BattlesIdRouteWithChildren,
  BattlesIndexRoute: BattlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
